### ISSUE TITLE
Eclipse android development

### ISSUE THREAD

**Issue by johnconnorskynet** [BartoszJarocki/android-boilerpipe#1]
Hello, 

I need some help, i would like to use boilerpipe-android in an eclipse environement and look for a way to proceed.

Thanx.

**Comment by BartoszJarocki** [comment]
It's just a java library, so I belive following these steps - http://stackoverflow.com/questions/11213871/creating-a-java-library-with-eclipse will solve your problem.

Nevertheless, I strongly suggest switiching to Android Studio.

**Comment by mkotsollaris** [comment]
Is there any `JAR` that we can import, or we must hard copy all the files? I am using Android Studio.
